EotE_Encounter/Models/Encounter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using EotE_Encounter.Models;

namespace EotE_Encounter.Models
{
    public class Encounter
    {
        public Encounter()
        {
            Round = 1;
            Characters = new List<Character>();
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public byte Round { get; set; }
        [StringLength(2000)]
        public string Notes { get; set; }

        public List<Character> Characters { get; set; }
    }

}

EotE_Encounter/Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EotE_Encounter.Models;

namespace EotE_Encounter.Controllers
{
    public class CharacterController : Controller
    {

        public CharacterController()
        {
        }

        public ActionResult CreateCharacter(string encounterJSON)
        {
            Encounter encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(encounterJSON);
            TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
            return PartialView("Add");
        }
        
        public ActionResult Add(Character character)
        {
            if (ModelState.IsValid)
            {
                Encounter encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(TempData["encounter"].ToString());
                character.SetIniativeScore();
                List<Character> encounterCharacters = encounter.Characters;
               
                //if the encounter list is empty, set the character turn to true, and id of 1.
                if(encounterCharacters.Count <= 0)
                {
                    character.Turn = true;
                    character.Id = 1;
                }
                else
                {
                    //give new character an ID that is +1 of the current MAX id of the all the characters.
                    character.Id = encounterCharacters.OrderByDescending(c => c.Id).FirstOrDefault().Id + 1;

                    //if added character has a greater iniativeScore than the current character with greatest iniativeScore, then set added character turn to true
                    if (character.IniativeScore > encounterCharacters.OrderByDescending(c => c.IniativeScore).First().IniativeScore)
                    {
                        foreach(Character characterInEncounter in encounterCharacters)
                        {
                            characterInEncounter.Turn = false;
                        }
                        character.Turn = true;
                    }
                }
                encounterCharacters.Add(character);
                encounter.Characters = encounterCharacters.OrderByDescending(c => c.IniativeScore).ToList();
                TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
                return RedirectToAction("Details", "Encounter");
            }
            return PartialView();
        }


        public ActionResult Edit(Character character, string encounterJSON)
        {
            if (ModelState.IsValid)
            {
                Encounter encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(encounterJSON);
                Character oldCharacter = encounter.Characters.Where(c => c.Id.Equals(character.Id)).SingleOrDefault();
                var oldCharacterIndex = encounter.Characters.IndexOf(oldCharacter);
                oldCharacter.Name = character.Name;
                oldCharacter.Notes = character.Notes;
                //if the number if triupmhs, successes, or advantages have changed, update the IniativeScore
                if (oldCharacter.Triumphs != character.Triumphs || oldCharacter.Succeses != character.Succeses || oldCharacter.Advantages != character.Advantages)
                {
                    oldCharacter.Triumphs = character.Triumphs;
                    oldCharacter.Succeses = character.Succeses;
                    oldCharacter.Advantages = character.Advantages;
                    oldCharacter.SetIniativeScore();
                    if (oldCharacter.IniativeScore >= encounter.Characters.OrderByDescending(c => c.IniativeScore).First().IniativeScore)
                    {
                        encounter.Characters.OrderByDescending(c => c.IniativeScore).First().Turn = false;
                        oldCharacter.Turn = true;
                    }
                }
                encounter.Characters[oldCharacterIndex] = oldCharacter;
                TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
                return RedirectToAction("Details", "Encounter");
            }
            return PartialView("Details", character);
        }

        public ActionResult Details(int characterId, string encounterJSON)
        {
            Encounter encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(encounterJSON);
            Character character = encounter.Characters.Where(c => c.Id.Equals(characterId)).SingleOrDefault();
            ViewBag.EncounterName = encounter.Name;
            ViewBag.EncounterCharacters = encounter.Characters;
            TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
            return PartialView("Details", character);
        }

        public ActionResult Delete(int characterId, string encounterJSON)
        {
            Encounter encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(encounterJSON);
            Character character = encounter.Characters.Where(c => c.Id == characterId).SingleOrDefault();
            List<Character> characters = encounter.Characters.ToList().OrderByDescending(c => c.IniativeScore).ToList();
            int characterIndex = characters.IndexOf(character);

            if(character.Turn == true)
            {
                if (character.Id != characters.LastOrDefault().Id)
                {
                    characters[characterIndex + 1].Turn = true;
                }
                else
                {
                    characters.FirstOrDefault().Turn = true;
                }
            }

            encounter.Characters.Remove(character);
            TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
            return RedirectToAction("Details", "Encounter");
        }

        //called when you want to change the turn to the next or previous character in the initiative order
        public ActionResult ChangeTurn(string direction, string encounterJSON)
        {
            const string NEXT = "next";
            const string PREV = "prev";
            Encounter encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(encounterJSON);
            List<Character> characters = encounter.Characters.OrderByDescending(c => c.IniativeScore).ToList();

            //if there is no one in the encounter, don't do anything...just return the empty encounter
            if(characters.Count < 1)
            {
                TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
                return RedirectToAction("Details", "Encounter");
            }
            Character currentTurnCharacter = encounter.Characters.Where(c => c.Turn == true).SingleOrDefault();
            currentTurnCharacter.Turn = false;
            int currentTurnCharacterIndex = characters.IndexOf(currentTurnCharacter);
            //previous turn
            if (direction == PREV)
            {
                //detect if character is at the top of the list
                if (currentTurnCharacter.Id != characters.FirstOrDefault().Id)
                {
                    characters[currentTurnCharacterIndex - 1].Turn = true;
                }
                else
                {
                    characters.LastOrDefault().Turn = true;
                }
            }else if (direction== NEXT)
            {
                if (currentTurnCharacter.Id != characters.LastOrDefault().Id)
                {
                    characters[currentTurnCharacterIndex + 1].Turn = true;
                }
                else
                {
                    characters.FirstOrDefault().Turn = true;
                }
            }
            encounter.Characters = characters;
            TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
            return RedirectToAction("Details", "Encounter");
        }
    }
}

EotE_Encounter/Controllers/EncounterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EotE_Encounter.Models;
using Microsoft.EntityFrameworkCore;

namespace EotE_Encounter.Controllers
{
    public class EncounterController : Controller
    {
        public EncounterController()
        {
        }

        /*sets encounter name is "Encounter" if none is given
         *saves encounter to DB
         *
         */
        [HttpPost]
        public ActionResult Create(Encounter encounter)
        {
            //consider doing this in encounter controller
            if (String.IsNullOrWhiteSpace(encounter.Name))
            {
                encounter.Name = "Encounter";
            }
            TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
            return RedirectToAction("Details");
        }

        /* gets the encounter from db based on encounterId.
         * gets list of characters that encounterId's match the encounter.
         * sorts list of characters based on IniativeScore
         */
        public ActionResult Details(Encounter encounter)
        {

            encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(TempData["encounter"].ToString());
            encounter.Characters = encounter.Characters.OrderByDescending(c => c.IniativeScore).ToList();
            TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
            return PartialView("Details", encounter);
        }

        /*changes the iniative order of the character passed. This is done by swapping the iniativeScore of the 
         * character passed with either the character below or above it, which is passed via the direction variable.
         * It the character is at the top of the list, and moved up then the character is moved to the bottom of the list.
         * The opposite occurs if the character is at the bottom of the list.
         */
        public ActionResult ChangeInitiative(int characterId, string direction, string encounterJSON)
        {
            const string MOVE_UP = "up";
            const string MOVE_DOWN = "down";
            Encounter encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(encounterJSON);
            List<Character> characters = encounter.Characters.OrderByDescending(c => c.IniativeScore).ToList();

            //if there is one character in the encounter, don't do anything...just return the encounter as is
            //we don't need to change the initiative of one person
            if (characters.Count <= 1)
            {
                TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
                return RedirectToAction("Details", "Encounter");
            }

            Character movedCharacter = encounter.Characters.Where(c => c.Id == characterId).SingleOrDefault();

            //move character up
            if(direction == MOVE_UP)
            {
                //detect if character is at the top of the list
                if(movedCharacter.Id != characters.FirstOrDefault().Id)
                {
                    short tempInitiativeScore = movedCharacter.IniativeScore;
                    int movedCharacterIndex = characters.IndexOf(movedCharacter);
                    movedCharacter.IniativeScore = characters[movedCharacterIndex - 1].IniativeScore;
                    characters[movedCharacterIndex - 1].IniativeScore = tempInitiativeScore;

                    if(characters[movedCharacterIndex - 1].Turn == true)
                    {
                        characters[movedCharacterIndex - 1].Turn = false;
                        movedCharacter.Turn = true;
                    }
                }
                else
                {
                    
                    for(int i = 1; i < characters.Count; i++)
                    {
                        short tempInitiativeScore = movedCharacter.IniativeScore;
                        movedCharacter.IniativeScore = characters[i].IniativeScore;
                        characters[i].IniativeScore = tempInitiativeScore;
                    }

                    if (movedCharacter.Turn == true)
                    {
                        int movedCharacterIndex = characters.IndexOf(movedCharacter);
                        movedCharacter.Turn = false;
                        characters[movedCharacterIndex + 1].Turn = true;
                    }
                }
            }else if (direction == MOVE_DOWN)
            {
                if(movedCharacter.Id != characters.LastOrDefault().Id)
                {
                    short tempInitiativeScore = movedCharacter.IniativeScore;
                    int movedCharacterIndex = characters.IndexOf(movedCharacter);
                    movedCharacter.IniativeScore = characters[movedCharacterIndex + 1].IniativeScore;
                    characters[movedCharacterIndex + 1].IniativeScore = tempInitiativeScore;

                    if (movedCharacter.Turn == true)
                    {
                        movedCharacter.Turn = false;
                        characters[movedCharacterIndex + 1].Turn = true;
                    }
                }
                else
                {
                    for(int i = characters.Count - 2; i >= 0; i--)
                    {
                        short tempInitiativeScore = movedCharacter.IniativeScore;
                        movedCharacter.IniativeScore = characters[i].IniativeScore;
                        characters[i].IniativeScore = tempInitiativeScore;
                    }
                }
            }
            encounter.Characters = characters;
            TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
            return RedirectToAction("Details");
        }

        //deletes all characters from encounter
        public ActionResult Clear(string encounterJSON)
        {
            Encounter encounter = Newtonsoft.Json.JsonConvert.DeserializeObject<Encounter>(encounterJSON);
            encounter.Characters.Clear();
            TempData["encounter"] = Newtonsoft.Json.JsonConvert.SerializeObject(encounter);
            return RedirectToAction("Details");

        }
    }
}

EotE_Encounter/Views/Encounter/Create.cshtml
@model EotE_Encounter.Models.Encounter
<h3>Add an Encounter</h3>
<form id="create-encounter" asp-action="Create" asp-controller="Encounter" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#encounter-container" >
    <div class="form-group">
        @Html.LabelFor(e => e.Name)
        @Html.TextBoxFor(e => e.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Create</button>
    </div>
</form>

EotE_Encounter/Views/Encounter/Details.cshtml
@model EotE_Encounter.Models.Encounter


<h3 class="encounter-title">@Model.Name</h3>
<div>
    <div id="iniative-list" class="list-group">
        <a id="add-character-item" asp-action="CreateCharacter" asp-controller="Character" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#character-container" class="list-group-item"><strong>Add a new character</strong></a>
        @{
            if (Model.Characters != null)
            {
                foreach (Character character in Model.Characters)
                {
                    if (character.Turn == true)
                    {
                        <div class="list-group-item current-turn">
                            <div class="row">
                                <div id="iniative-character-name" class="col-md-11">
                                    <a asp-action="Details" asp-controller="Character" asp-route-characterId="@character.Id" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#character-container" class="iniative-item"><h4>@character.Name</h4></a>
                                </div>
                                <div id="iniative-move-arrows" class="col-md-1">
                                    <a asp-action="ChangeInitiative" asp-controller="Encounter" asp-route-characterId="@character.Id" asp-route-direction="up" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#encounter-container">
                                        <span class="glyphicon glyphicon-menu-up"></span>
                                    </a>
                                    <a asp-action="ChangeInitiative" asp-controller="Encounter" asp-route-characterId="@character.Id" asp-route-direction="down" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#encounter-container">
                                        <span class="glyphicon glyphicon-menu-down display-block"></span>
                                    </a>
                                </div>
                            </div>
                        </div>

                    }
                    else
                    {
                        <div class="list-group-item">
                            <div class="row">
                                <div id="iniative-character-name" class="col-md-11">
                                    <a asp-action="Details" asp-controller="Character" asp-route-characterId="@character.Id" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#character-container" class="iniative-item"><h4>@character.Name</h4></a>
                                </div>
                                <div id="iniative-move-arrows" class="col-md-1">
                                    <a asp-action="ChangeInitiative" asp-controller="Encounter" asp-route-characterId="@character.Id" asp-route-direction="up" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#encounter-container">
                                        <span class="glyphicon glyphicon-menu-up"></span>
                                    </a>
                                    <a asp-action="ChangeInitiative" asp-controller="Encounter" asp-route-characterId="@character.Id" asp-route-direction="down" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#encounter-container">
                                        <span class="glyphicon glyphicon-menu-down display-block"></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    }
                }
            }
        }
    </div>
    <div class="row" id="encounter-controls">
        <div class="col-sm-2">
            <a class="btn btn-default" asp-action="ChangeTurn" asp-controller="Character" asp-route-direction="prev" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#encounter-container">Previous</a>
        </div>
        <div class="col-sm-2">
            <a class="btn btn-default" asp-action="ChangeTurn" asp-controller="Character" asp-route-direction="next" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#encounter-container">Next</a>
        </div>
        <div class="col-sm-offset-9">
            <a id ="clear-encounter" class="btn btn-danger" asp-action="Clear" asp-controller="Encounter" asp-route-encounterJSON="@Json.Serialize(Model)" data-ajax="false" data-ajax-mode="replace" data-ajax-update="#encounter-container" onclick="return confirmClear()">Clear Encounter</a>
        </div>
    </div>
</div>

<script>
    //prompt user for clearing the encounter
    //sets the character container to empty in the event a character was selected when the encounter was cleared
    //also removes the bottom bar of the character container for the same reason.
    function confirmClear() {
        if (confirm("Are you sure you want to clear @Model.Name?")) {
            $("#clear-encounter").attr("data-ajax", "true");
            $("#character-container").html("").removeClass("bottom-colored-bar");
            return true;

        } else {
            return false;

        }

    }



    //when a character in the encounter list is clicked, they become highlighted,
    //show the bottom bar on the character container for editting the character
    //remove highlight from previous selected character
    $(".iniative-item").click(function () {
        $(".selected-character").removeClass("selected-character");
        $("#character-container").addClass("bottom-colored-bar");
        $(this).parents(".list-group-item").addClass("selected-character");

    });

    //add the bottom bar to the character container when adding a character
    $("#add-character-item").click(function () {
        $("#character-container").addClass("bottom-colored-bar");
    });
</script>

EotE_Encounter/Views/Encounter/Notes.cshtml
@model EotE_Encounter.Models.Encounter


@Html.TextAreaFor(e => e.Notes, new { @placeholder = "Enter encounter notes here..."})